# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABaRw2cyhVPkbQVJdKf2LZOdRQoDsCpT
"""

import pandas as pd

df_backup = pd.read_csv("Amazon.csv")
df = df_backup.copy()
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.head()
df.info()

df = df.drop_duplicates()


df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df["orderdate"] = pd.to_datetime(df["orderdate"])

df["year"] = df["orderdate"].dt.year
df["month"] = df["orderdate"].dt.month
df["year_month"] = df["orderdate"].dt.strftime("%Y-%m")

numeric_columns = [
    "quantity",
    "unitprice",
    "discount",
    "tax",
    "shippingcost",
    "totalamount"
]


df[numeric_columns] = df[numeric_columns].apply(
    pd.to_numeric,
    errors="coerce"
)

text_columns = [
    "customername",
    "customerid",
    "productid",
    "productname",
    "category",
    "brand",
    "paymentmethod",
    "orderstatus",
    "city",
    "state",
    "country",
    "sellerid"
]
for column in text_columns:
  df[column] = (
      df[column]
      .astype(str)
      .str.strip()
      .str.title()
  )

df.fillna({
    "discount":0,
    "shippingcost":0,
    "tax":0
}, inplace=True)

df["brand"] = df['brand'].fillna("Não informado")

df[df["quantity"] <= 0]

df[df["unitprice"] <= 0]

df[df["totalamount"] <= 0]

df["gross_amount"] = (
    df["quantity"]*
    df["unitprice"]
).round(2)

df["discount_amount"] = (
    df["gross_amount"] *
    df["discount"]
).round(2)

df["net_revenue"] = (
    df["totalamount"] -
    df["tax"] -
    df["shippingcost"]
).round(2)


df["ticket"] = pd.cut(
    df["totalamount"],
    bins=[0,100,500,1000,float("inf")],
    labels=[
        "Baixo",
        "Médio",
        "Alto",
        "Premium"
    ]
)

df["customerid"].nunique()

df["productid"].nunique()

df["sellerid"].nunique()

df.head()

from google.colab import files

df.to_csv("Amazon_processados.csv", index=False)

files.download("Amazon_processados.csv")

